# Generated by Django 4.1.3 on 2023-01-13 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_entry_due_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='due_by',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 0, 15, 57, 152034)),
        ),
    ]
